version: "3.9"

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/app
    ports:
      - "3000:3000"
    links:
      - postgres
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=maquina_facturadora

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"
    depends_on:
      - postgres
