name: CI

on:
  push:
    branches:
      - main
    paths:
      - maquina_facturadora/**
      #- maquina_facturadora_front/**
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  build_back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm install --include=optional
      - run: npx nx run back-emergency-control-verde:build

  test_back:
    needs: [build_back]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm install --include=optional
      - run: npx nx run back-emergency-control-verde:test
  
  lint_back:
    needs: [test_back]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm install --include=optional
      - run: npx nx run back-emergency-control-verde:lint
